"""add cost centers

Revision ID: 421cb6fd4ade
Revises: 8a05761988a3
Create Date: 2026-06-13 12:27:07.083044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '421cb6fd4ade'
down_revision: Union[str, Sequence[str], None] = '8a05761988a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('accounts', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_connection_id'), table_name='accounts')
    op.drop_index(op.f('ix_asset_values_asset_date'), table_name='asset_values')
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_assets_company_id'), table_name='assets')
    op.alter_column('bank_connections', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_bank_connections_company_id'), table_name='bank_connections')
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.alter_column('budgets', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_budgets_company_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_recurring_lookup'), table_name='budgets', postgresql_where='(is_recurring = true)')
    op.alter_column('categories', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_categories_company_id'), table_name='categories')
    op.alter_column('category_groups', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_category_groups_company_id'), table_name='category_groups')
    op.drop_index(op.f('ix_company_members_company_id'), table_name='company_members')
    op.drop_index(op.f('ix_company_members_user_id'), table_name='company_members')
    op.alter_column('fx_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_goals_company_id'), table_name='goals')
    op.drop_index(op.f('ix_import_logs_company_id'), table_name='import_logs')
    op.alter_column('payee_mapping', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_payee_mapping_company_id'), table_name='payee_mapping')
    op.alter_column('payees', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_payees_company_id'), table_name='payees')
    op.alter_column('recurring_transactions', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('recurring_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_recurring_transactions_company_id'), table_name='recurring_transactions')
    op.alter_column('rules', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_rules_company_id'), table_name='rules')
    op.drop_index(op.f('ix_transaction_attachments_transaction_id'), table_name='transaction_attachments')
    op.drop_index(op.f('ix_transaction_attachments_user_id'), table_name='transaction_attachments')
    op.add_column('transactions', sa.Column('cost_center_id', sa.UUID(), nullable=True))
    op.alter_column('transactions', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transactions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('transactions', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payee_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transfer_pair_id'), table_name='transactions', postgresql_where='(transfer_pair_id IS NOT NULL)')
    op.create_foreign_key(None, 'transactions', 'cost_centers', ['cost_center_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_index(op.f('ix_transactions_transfer_pair_id'), 'transactions', ['transfer_pair_id'], unique=False, postgresql_where='(transfer_pair_id IS NOT NULL)')
    op.create_index(op.f('ix_transactions_payee_id'), 'transactions', ['payee_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.alter_column('transactions', 'raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('transactions', 'notes',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('transactions', 'cost_center_id')
    op.create_index(op.f('ix_transaction_attachments_user_id'), 'transaction_attachments', ['user_id'], unique=False)
    op.create_index(op.f('ix_transaction_attachments_transaction_id'), 'transaction_attachments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_rules_company_id'), 'rules', ['company_id'], unique=False)
    op.alter_column('rules', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_recurring_transactions_company_id'), 'recurring_transactions', ['company_id'], unique=False)
    op.alter_column('recurring_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recurring_transactions', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_payees_company_id'), 'payees', ['company_id'], unique=False)
    op.alter_column('payees', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_payee_mapping_company_id'), 'payee_mapping', ['company_id'], unique=False)
    op.alter_column('payee_mapping', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_import_logs_company_id'), 'import_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_goals_company_id'), 'goals', ['company_id'], unique=False)
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fx_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_company_members_user_id'), 'company_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_company_members_company_id'), 'company_members', ['company_id'], unique=False)
    op.create_index(op.f('ix_category_groups_company_id'), 'category_groups', ['company_id'], unique=False)
    op.alter_column('category_groups', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_categories_company_id'), 'categories', ['company_id'], unique=False)
    op.alter_column('categories', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_budgets_recurring_lookup'), 'budgets', ['company_id', 'category_id', 'month'], unique=False, postgresql_where='(is_recurring = true)')
    op.create_index(op.f('ix_budgets_company_id'), 'budgets', ['company_id'], unique=False)
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    op.create_index(op.f('ix_bank_connections_company_id'), 'bank_connections', ['company_id'], unique=False)
    op.alter_column('bank_connections', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_assets_company_id'), 'assets', ['company_id'], unique=False)
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_asset_values_asset_date'), 'asset_values', ['asset_id', 'date'], unique=False)
    op.create_index(op.f('ix_accounts_connection_id'), 'accounts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.alter_column('accounts', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('cost_centers')
    # ### end Alembic commands ###
