"""Add code and position to categories

Revision ID: 8a05761988a3
Revises: 288e3e42af9c
Create Date: 2026-05-12 10:53:19.026697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a05761988a3'
down_revision: Union[str, Sequence[str], None] = '288e3e42af9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('categories', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('category_groups', sa.Column('code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_groups', 'code')
    op.drop_column('categories', 'position')
    op.drop_column('categories', 'code')
    # ### end Alembic commands ###
