"""add_recurrence_end_to_budget

Revision ID: 9cc22ebc012d
Revises: c6bac23ca72a
Create Date: 2026-07-28 20:52:06.040558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc22ebc012d'
down_revision: Union[str, Sequence[str], None] = 'c6bac23ca72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('recurrence_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'recurrence_end')
    # ### end Alembic commands ###
