"""add_cardholder_name

Revision ID: c6bac23ca72a
Revises: 77d6ee34176c
Create Date: 2026-07-07 08:20:37.619767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bac23ca72a'
down_revision: Union[str, Sequence[str], None] = '77d6ee34176c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cardholder_name', sa.String(length=255), nullable=True))
    op.drop_column('transactions', 'original_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('original_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'cardholder_name')
    # ### end Alembic commands ###
